<a href="https://colab.research.google.com/github/MuhammadAhmedMasood/deep-learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundamentals

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
print(torch.__version__)

2.11.0+cpu


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

###Creating Tensors

Pytorch tensors are created using `torch.tensor()`

In [4]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim # checking dimensions of the scalar

0

In [8]:
scalar.item() # get tensor back as python int

7

In [10]:
vector = torch.tensor([7,7]) # vector as input to the tensor
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [14]:
# matrix:

MATRIX = torch.tensor([[7,8],
                       [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[0]

tensor([7, 8])

In [17]:
MATRIX[1]

tensor([9, 8])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])

In [20]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Tensor can be of any shape and size

lower cases -> scalar and vectors

upper cases -> matrix and tensors

### Random Tensors:

Random tensors are impt because the way many NN learn is that they starts with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers`

In [31]:
# create a random tensors of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9848, 0.3544, 0.1127, 0.1057],
        [0.8429, 0.5840, 0.0336, 0.1152],
        [0.7235, 0.5772, 0.6828, 0.0671]])

In [32]:
random_tensor.ndim

2

In [34]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = [3, 224,224]) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [35]:
r_tensor = torch.rand(3,3,4,4,)
r_tensor

tensor([[[[0.6220, 0.7464, 0.7805, 0.7390],
          [0.6688, 0.7701, 0.9851, 0.0597],
          [0.5161, 0.1242, 0.4183, 0.3772],
          [0.7756, 0.9078, 0.7640, 0.8650]],

         [[0.3828, 0.1441, 0.9058, 0.9420],
          [0.2746, 0.6669, 0.4157, 0.2246],
          [0.3033, 0.4758, 0.8745, 0.3889],
          [0.1380, 0.3400, 0.0053, 0.6335]],

         [[0.5901, 0.2044, 0.2962, 0.4717],
          [0.1261, 0.2787, 0.4842, 0.6977],
          [0.9079, 0.6748, 0.2517, 0.2202],
          [0.0393, 0.8980, 0.8798, 0.8583]]],


        [[[0.5723, 0.5575, 0.0600, 0.0939],
          [0.3874, 0.5225, 0.5245, 0.2250],
          [0.8725, 0.3019, 0.7000, 0.7830],
          [0.4454, 0.3379, 0.8912, 0.2481]],

         [[0.0588, 0.4688, 0.6545, 0.7434],
          [0.8640, 0.7137, 0.1440, 0.5960],
          [0.3864, 0.3667, 0.8690, 0.6456],
          [0.9362, 0.0892, 0.5013, 0.5370]],

         [[0.8918, 0.1770, 0.9478, 0.6898],
          [0.8754, 0.1707, 0.2519, 0.7833],
          [0.1727, 0

In [36]:
r_tensor.shape

torch.Size([3, 3, 4, 4])

In [37]:
r_tensor.ndim

4

### Zeros and Ones:

In [38]:
# create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [42]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like:

In [49]:
# use torch.arange():

one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
# creating tensors-like:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
one_to_ten.dtype

torch.int64

### tensors datatypes:

**Notes:** Tensor datatypes one of the 3 big erros you'll run unto with pytorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [56]:
# Float 32 tensor:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what daat type of the tensor: float32 or float 16 etc
                               device = None, # by default it is cpu, can change to cuda - tensors must be on same device when we perform operations
                               requires_grad = False) # if we want pytorch to track gradients when tensors go into certain calculations
float_32_tensor

tensor([3., 6., 9.])

In [55]:
float_32_tensor.dtype

torch.float32

In [58]:
float_16_tensors = float_32_tensor.type(torch.float16)
float_16_tensors

tensor([3., 6., 9.], dtype=torch.float16)