<a href="https://colab.research.google.com/github/MuhammadAhmedMasood/deep-learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundamentals

In [1]:
# !nvidia-smi

In [2]:
import torch
print(torch.__version__)

2.11.0+cpu


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

###Creating Tensors

Pytorch tensors are created using `torch.tensor()`

In [4]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim # checking dimensions of the scalar

0

In [6]:
scalar.item() # get tensor back as python int

7

In [7]:
vector = torch.tensor([7,7]) # vector as input to the tensor
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# matrix:

MATRIX = torch.tensor([[7,8],
                       [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([9, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])

In [16]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Tensor can be of any shape and size

lower cases -> scalar and vectors

upper cases -> matrix and tensors

### Random Tensors:

Random tensors are impt because the way many NN learn is that they starts with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers`

In [20]:
# create a random tensors of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2861, 0.4455, 0.0570, 0.1707],
        [0.1385, 0.3161, 0.4209, 0.7807],
        [0.7623, 0.7634, 0.6232, 0.4931]])

In [21]:
random_tensor.ndim

2

In [22]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = [3, 224,224]) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [23]:
r_tensor = torch.rand(3,3,4,4,)
r_tensor

tensor([[[[0.4907, 0.7369, 0.7931, 0.7815],
          [0.4169, 0.7575, 0.5825, 0.1765],
          [0.1895, 0.6080, 0.3969, 0.8839],
          [0.8673, 0.8361, 0.4990, 0.0752]],

         [[0.9176, 0.9236, 0.6427, 0.5803],
          [0.4254, 0.6962, 0.1722, 0.8514],
          [0.0021, 0.5130, 0.6908, 0.2908],
          [0.6672, 0.8377, 0.3712, 0.1650]],

         [[0.1728, 0.6818, 0.1449, 0.7566],
          [0.2474, 0.4756, 0.4870, 0.4565],
          [0.9894, 0.2267, 0.6779, 0.3728],
          [0.9046, 0.6582, 0.7203, 0.0350]]],


        [[[0.7175, 0.7472, 0.8048, 0.1989],
          [0.6625, 0.2975, 0.0838, 0.5338],
          [0.5985, 0.0732, 0.7142, 0.5465],
          [0.9365, 0.2045, 0.1810, 0.0658]],

         [[0.6868, 0.4948, 0.4793, 0.5927],
          [0.4721, 0.3274, 0.8707, 0.0891],
          [0.2268, 0.3387, 0.7998, 0.7912],
          [0.8447, 0.8907, 0.2823, 0.2097]],

         [[0.3967, 0.8328, 0.9723, 0.3011],
          [0.4991, 0.1525, 0.5934, 0.5089],
          [0.4799, 0

In [24]:
r_tensor.shape

torch.Size([3, 3, 4, 4])

In [25]:
r_tensor.ndim

4

### Zeros and Ones:

In [26]:
# create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like:

In [30]:
# use torch.arange():

one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# creating tensors-like:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
one_to_ten.dtype

torch.int64

### tensors datatypes:

**Notes:** Tensor datatypes one of the 3 big erros you'll run unto with pytorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [33]:
# Float 32 tensor:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what daat type of the tensor: float32 or float 16 etc
                               device = None, # by default it is cpu, can change to cuda - tensors must be on same device when we perform operations
                               requires_grad = False) # if we want pytorch to track gradients when tensors go into certain calculations
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensors = float_32_tensor.type(torch.float16)
float_16_tensors

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensors * float_32_tensor # this works but in some cases it does give error

tensor([ 9., 36., 81.])

In [37]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [38]:
float_32_tensor*int_32_tensor # this works

tensor([ 9., 36., 81.])

In [39]:
long_tensor = torch.tensor([3,6,9], dtype = torch.long)
long_tensor

tensor([3, 6, 9])

In [40]:
long_tensor * float_32_tensor # this also works

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes):

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [41]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1262, 0.7536, 0.3486, 0.8965],
        [0.7606, 0.1121, 0.7395, 0.6884],
        [0.4624, 0.4325, 0.8020, 0.0922]])

In [42]:
# find out details about some_tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") # shape is attribute
print(f"Size of tensor: {some_tensor.size()}") # size() is a method
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1262, 0.7536, 0.3486, 0.8965],
        [0.7606, 0.1121, 0.7395, 0.6884],
        [0.4624, 0.4325, 0.8020, 0.0922]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Size of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations):

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [43]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [44]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [45]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [46]:
# try out Pytorch built-in functions:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### matrix multiplication:

two main ways to perform multiplication in NN and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product e.g a.b)

There are two rules that matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`

In [48]:
# element-wise multiplication:
print(f"{tensor}*{tensor}")
print(tensor*tensor)

tensor([1, 2, 3])*tensor([1, 2, 3])
tensor([1, 4, 9])


In [49]:
#matrix multiplication - this does a dot product
torch.matmul(tensor, tensor)

tensor(14)

In [50]:
# by hand:
(1*1)+(2*2)+(3*3)

14

In [51]:
# using a for-loop:
 %%time
 value = 0
 for i in range(len(tensor)):
  value+=tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 989 µs, sys: 922 µs, total: 1.91 ms
Wall time: 4.87 ms


In [52]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 920 µs, sys: 0 ns, total: 920 µs
Wall time: 919 µs


tensor(14)

In [54]:
# torch.matmul(torch.rand(2,3), torch.rand(2,3)) # errors as inner dimensions dont match

In [55]:
torch.matmul(torch.rand(4,2), torch.rand(2,5)).shape # rule number 2

torch.Size([4, 5])

### one of the most common errors in DL is shape errors

In [56]:
# shapes for matrix multiplication:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

In [57]:
tensor_A.shape

torch.Size([3, 2])

In [58]:
tensor_B.shape

torch.Size([3, 2])

In [60]:
# torch.mm(tensor_A, tensor_B) # torch.mm is same as torch.matmul (it's an alias for matmul)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose:

**transpose** switches the axes or dimensions of a given tensor

In [61]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [62]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [63]:
# matrix multiplication works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape} and tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape as above) and tensor_B.T = {tensor_B.T}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput Shape: ", output.shape)

Original shapes: tensor_A = torch.Size([3, 2]) and tensor_B = torch.Size([3, 2])
New Shapes: tensor_A = torch.Size([3, 2]) (same shape as above) and tensor_B.T = tensor([[ 7,  9, 11],
        [ 8, 10, 12]])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output Shape:  torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [64]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
x.dtype

torch.int64

In [66]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [67]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

the `torch.mean()` function requires a tensor of float32 datatype to work

In [68]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [69]:
# Find the sum:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [70]:
## Finding the positional min and max:

torch.argmin(x), x.argmin() # returns the index where the value is min

(tensor(0), tensor(0))

In [71]:
torch.argmax(x), x.argmax() # returns the index where value is max

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [72]:
# let's create a tensor
y = torch.arange(1., 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [73]:
y.dtype

torch.float32

In [74]:
# add extra dimension
# y_reshaped = y.reshape(1, 7) # this will give error as we are trying to squeeze 9 elements into 9
y_reshaped = y.reshape(1, 9) # 1 row and 9 cols


In [75]:
# change the view
z = y.view(1,9) # view similar to reshape, but shares the same memory of the tensor so z and y are pointing to the same memory
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
# changing z changes y because a view of a tensor shares the same memory as the original
z[:, 0] = 5
z, y, y_reshaped

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [81]:
# stack tensor on top of each other
y_stacked = torch.stack([y,y,y,y], dim = 0) # takes a list of tensors - dim = 0 is vstack and dim=1 is hstack
y_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [85]:
y_ver_stack = torch.vstack([y,y])
y_ver_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [86]:
y_hor_stack = torch.hstack([y,y])
y_hor_stack

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [96]:
y_reshaped, y_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [94]:
# squeeze (removes all single dimensions from the tensor) and unsqueeze:
y_squeeze = torch.squeeze(y_reshaped)
y_squeeze

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
y_squeeze.shape # 1 dimension removed

torch.Size([9])

In [100]:
# unsqueeze - adds a single dimension to a target tensor
y_unsqueeze = torch.unsqueeze(y_squeeze, dim = 0) # can give dim = 1
y_unsqueeze, y_unsqueeze.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [107]:
y_unsqueeze_2 = torch.unsqueeze(y_unsqueeze, dim = 2) # can give dim = 1
y_unsqueeze_2, y_unsqueeze_2.shape

(tensor([[[5.],
          [2.],
          [3.],
          [4.],
          [5.],
          [6.],
          [7.],
          [8.],
          [9.]]]),
 torch.Size([1, 9, 1]))

In [109]:
# torch.permute - rearranges the dimensions in a specified order - returns a view
x_original = torch.rand(size = (224,224,3)) # [heights, width, colour_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # takes in dims as input - shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Prevous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Prevous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [112]:
# one thing is like view, x_permuted and x_original are pointing to the same memory so let's check:
x_original[0,0,0] = 694848
x_original

tensor([[[6.9485e+05, 9.7398e-01, 7.6126e-01],
         [7.3301e-01, 6.1795e-02, 3.5781e-01],
         [1.1384e-01, 7.8202e-01, 1.4589e-01],
         ...,
         [5.1116e-01, 1.6621e-01, 5.1816e-01],
         [6.3274e-01, 5.5861e-01, 6.9730e-01],
         [3.2773e-01, 5.7623e-03, 8.5534e-01]],

        [[7.9998e-01, 9.4412e-01, 5.5113e-01],
         [1.5544e-01, 3.2946e-01, 4.5469e-02],
         [5.2214e-01, 2.7724e-01, 3.1411e-01],
         ...,
         [6.7526e-01, 9.8510e-01, 9.1344e-01],
         [5.2427e-02, 4.9446e-02, 1.2271e-01],
         [1.3745e-02, 8.7370e-02, 8.6881e-01]],

        [[1.0253e-01, 6.2435e-01, 7.2814e-02],
         [3.6849e-01, 6.6419e-01, 8.1918e-02],
         [4.6894e-02, 5.7376e-01, 9.6166e-02],
         ...,
         [2.8347e-01, 2.4850e-01, 4.8867e-01],
         [9.9930e-01, 3.0388e-01, 9.5414e-01],
         [9.8442e-01, 1.0566e-01, 3.6446e-01]],

        ...,

        [[3.7161e-01, 2.0134e-01, 6.4543e-01],
         [4.5158e-01, 5.6419e-01, 4.3691e-02]

In [113]:
x_permuted[0,0,0] # so changed

tensor(694848.)

In [114]:
x_original.dtype

torch.float32

In [115]:
x_permuted.dtype

torch.float32

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with Numpy

In [116]:
# create a tensor
a = torch.arange(1,10).reshape(1,3,3)
a, a.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [117]:
# let's index on our new tensor
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [118]:
# indexing on the middle bracked
a[0][0]

tensor([1, 2, 3])

In [119]:
# indexing the most inner bracket
a[0][0][0]

tensor(1)

In [121]:
a.dim()

3

In [122]:
# to print element 9:
a[0][2][2]

tensor(9)

In [123]:
# can also use ":" to select all of a target dimension
a[:, 0]

tensor([[1, 2, 3]])

In [124]:
# get all values of 0th and 1st dimension, but only index 1 of 2nd dimension:
a[:,:,1]

tensor([[2, 5, 8]])

In [125]:
# get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension:
a[:,1,1]

tensor([5])

In [126]:
# get index 0 of 0th dimension and 1st dimension and all values of 2nd dimension
a[0,0,:]

tensor([1, 2, 3])

In [127]:
# indexing to get 3, 6, 9
a[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors and Numpy

Numpy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionality to interact with it.

* Data in Numpy, want in Pytroch tensor -> `torch.from)numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [128]:
# Numpy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [134]:
array.dtype

dtype('float64')

In [129]:
# the default tensor dtype is float32, but when changing from numpy to tensor, we get get float64 as seen above.
# we can change that to float32 by:

# tensor = torch.from_numpy(array).type(torch.float32)

In [130]:
# change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [131]:
# new tensor in memory

In [132]:
# tensor to numpy
tensor_N = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor_N, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]), array([1., 2., 3., 4., 5., 6., 7.]))

In [133]:
numpy_tensor.dtype

dtype('float64')

In [135]:
tensor_N.dtype

torch.float32

In [136]:
# so when changing back to numpy from tensor, the datatype changes from float32 to float64
# but this doesnt happen when we convert numpy array to a tensor

In [138]:
 # change the value of tensor, what will this do to numpy array?
 tensor_N + 1
 tensor_N, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]), array([1., 2., 3., 4., 5., 6., 7.]))

In [139]:
# so numpy array gets stored in a separate memory

## Reproducibility: trying to take random out of random

In short how a neural network learns:

`start with random number -> tensor operations -> update random numbers to try and make better representations of the data -> again -> again -> again...`

To reduce the randomness in NN and Pytorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [141]:
# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7697, 0.5715, 0.8709, 0.0914],
        [0.8080, 0.2657, 0.4046, 0.2527],
        [0.9376, 0.2318, 0.4598, 0.0970]])
tensor([[0.4832, 0.0290, 0.2618, 0.9925],
        [0.9963, 0.7613, 0.4577, 0.5220],
        [0.9397, 0.9106, 0.4312, 0.8335]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
