<a href="https://colab.research.google.com/github/MuhammadAhmedMasood/deep-learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundamentals

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [59]:
import torch
print(torch.__version__)

2.11.0+cpu


In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

###Creating Tensors

Pytorch tensors are created using `torch.tensor()`

In [61]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [62]:
scalar.ndim # checking dimensions of the scalar

0

In [63]:
scalar.item() # get tensor back as python int

7

In [64]:
vector = torch.tensor([7,7]) # vector as input to the tensor
vector

tensor([7, 7])

In [65]:
vector.ndim

1

In [66]:
vector.shape

torch.Size([2])

In [67]:
# matrix:

MATRIX = torch.tensor([[7,8],
                       [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [68]:
MATRIX.ndim

2

In [69]:
MATRIX[0]

tensor([7, 8])

In [70]:
MATRIX[1]

tensor([9, 8])

In [71]:
MATRIX.shape

torch.Size([2, 2])

In [72]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])

In [73]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [74]:
TENSOR.ndim

3

In [75]:
TENSOR.shape

torch.Size([1, 3, 3])

In [76]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Tensor can be of any shape and size

lower cases -> scalar and vectors

upper cases -> matrix and tensors

### Random Tensors:

Random tensors are impt because the way many NN learn is that they starts with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers`

In [77]:
# create a random tensors of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3568, 0.3505, 0.6454, 0.0479],
        [0.4863, 0.0504, 0.5951, 0.5944],
        [0.7386, 0.9744, 0.7435, 0.9077]])

In [78]:
random_tensor.ndim

2

In [79]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = [3, 224,224]) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [80]:
r_tensor = torch.rand(3,3,4,4,)
r_tensor

tensor([[[[7.5287e-01, 8.2334e-01, 3.7950e-01, 3.0919e-01],
          [8.8870e-01, 7.0153e-02, 2.9472e-01, 4.3905e-01],
          [8.8743e-01, 6.5254e-01, 4.6008e-01, 5.0631e-01],
          [6.2393e-01, 5.2505e-01, 2.1684e-01, 9.8368e-01]],

         [[9.1856e-01, 5.8884e-01, 8.7931e-02, 2.8014e-01],
          [7.3892e-01, 6.6100e-01, 8.3206e-01, 9.8775e-01],
          [3.8608e-01, 5.8418e-01, 1.5046e-01, 3.2211e-01],
          [9.2098e-01, 7.4650e-01, 2.5237e-01, 9.0387e-01]],

         [[5.4808e-01, 3.7987e-01, 3.2725e-02, 1.2593e-01],
          [5.9911e-01, 9.8373e-01, 6.3095e-01, 1.5779e-01],
          [8.3292e-01, 8.9481e-01, 9.3267e-01, 7.7547e-01],
          [5.1918e-01, 1.4595e-01, 5.4464e-01, 9.0675e-01]]],


        [[[1.6530e-01, 1.1513e-01, 1.3040e-01, 3.0216e-01],
          [7.4502e-02, 5.5791e-01, 7.5634e-02, 4.4724e-01],
          [9.8870e-01, 3.0516e-01, 3.7381e-01, 3.5460e-01],
          [6.2321e-01, 9.7902e-01, 2.7755e-01, 4.9909e-01]],

         [[4.1386e-02, 4.7132e

In [81]:
r_tensor.shape

torch.Size([3, 3, 4, 4])

In [82]:
r_tensor.ndim

4

### Zeros and Ones:

In [83]:
# create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [84]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [85]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [86]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like:

In [87]:
# use torch.arange():

one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
# creating tensors-like:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [89]:
one_to_ten.dtype

torch.int64

### tensors datatypes:

**Notes:** Tensor datatypes one of the 3 big erros you'll run unto with pytorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [90]:
# Float 32 tensor:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what daat type of the tensor: float32 or float 16 etc
                               device = None, # by default it is cpu, can change to cuda - tensors must be on same device when we perform operations
                               requires_grad = False) # if we want pytorch to track gradients when tensors go into certain calculations
float_32_tensor

tensor([3., 6., 9.])

In [91]:
float_32_tensor.dtype

torch.float32

In [92]:
float_16_tensors = float_32_tensor.type(torch.float16)
float_16_tensors

tensor([3., 6., 9.], dtype=torch.float16)

In [94]:
float_16_tensors * float_32_tensor # this works but in some cases it does give error

tensor([ 9., 36., 81.])

In [95]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [97]:
float_32_tensor*int_32_tensor # this works

tensor([ 9., 36., 81.])

In [100]:
long_tensor = torch.tensor([3,6,9], dtype = torch.long)
long_tensor

tensor([3, 6, 9])

In [102]:
long_tensor * float_32_tensor # this also works

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes):

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [103]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5235, 0.7585, 0.5634, 0.4641],
        [0.3306, 0.6590, 0.6009, 0.6081],
        [0.7469, 0.1442, 0.4777, 0.0997]])

In [106]:
# find out details about some_tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") # shape is attribute
print(f"Size of tensor: {some_tensor.size()}") # size() is a method
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5235, 0.7585, 0.5634, 0.4641],
        [0.3306, 0.6590, 0.6009, 0.6081],
        [0.7469, 0.1442, 0.4777, 0.0997]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Size of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations):

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [108]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [110]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [111]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [112]:
# try out Pytorch built-in functions:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [113]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### matrix multiplication:

two main ways to perform multiplication in NN and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product e.g a.b)

There are two rules that matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`

In [115]:
# element-wise multiplication:
print(f"{tensor}*{tensor}")
print(tensor*tensor)

tensor([1, 2, 3])*tensor([1, 2, 3])
tensor([1, 4, 9])


In [116]:
#matrix multiplication - this does a dot product
torch.matmul(tensor, tensor)

tensor(14)

In [117]:
# by hand:
(1*1)+(2*2)+(3*3)

14

In [119]:
# using a for-loop:
 %%time
 value = 0
 for i in range(len(tensor)):
  value+=tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 993 µs, sys: 0 ns, total: 993 µs
Wall time: 1.02 ms


In [120]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 0 ns, sys: 749 µs, total: 749 µs
Wall time: 623 µs


tensor(14)

In [121]:
torch.matmul(torch.rand(2,3), torch.rand(2,3)) # errors as inner dimensions dont match

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [122]:
torch.matmul(torch.rand(4,2), torch.rand(2,5)).shape # rule number 2

torch.Size([4, 5])

### one of the most common errors in DL is shape errors

In [123]:
# shapes for matrix multiplication:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

In [125]:
tensor_A.shape

torch.Size([3, 2])

In [126]:
tensor_B.shape

torch.Size([3, 2])

In [124]:
torch.mm(tensor_A, tensor_B) # torch.mm is same as torch.matmul (it's an alias for matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose:

**transpose** switches the axes or dimensions of a given tensor

In [130]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [129]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [134]:
# matrix multiplication works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape} and tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape as above) and tensor_B.T = {tensor_B.T}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput Shape: ", output.shape)

Original shapes: tensor_A = torch.Size([3, 2]) and tensor_B = torch.Size([3, 2])
New Shapes: tensor_A = torch.Size([3, 2]) (same shape as above) and tensor_B.T = tensor([[ 7,  9, 11],
        [ 8, 10, 12]])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output Shape:  torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [136]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [140]:
x.dtype

torch.int64

In [137]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [138]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

the `torch.mean()` function requires a tensor of float32 datatype to work

In [146]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [147]:
# Find the sum:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [150]:
## Finding the positional min and max:

torch.argmin(x), x.argmin() # returns the index where the value is min

(tensor(0), tensor(0))

In [152]:
torch.argmax(x), x.argmax() # returns the index where value is max

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way